# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53e7bfb4cd4d4d120e6571729bb9cc28ea7e031eb8044cc27d193aaaa085ad73d1c34b64c4d6a259adb7053db18bec03ceebbbe33e259e52f610c5916a52e919

test:
  secret_key_base: e3cb6f3ab22e5f9d3d8e28182a21a01c2b1b3a8dd4cc29ba82d4984dd3aa948a0dfd81f7049cddf55e95b82182e2adf091ca5202a2bfd0a2a49e3ed2ad44abc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
